apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentspring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agentspring-app
  template:
    metadata:
      labels:
        app: agentspring-app
    spec:
      containers:
      - name: app
        image: agentspring:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: agentspring-config
        - secretRef:
            name: agentspring-secrets
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10 