apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentspring-celery-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agentspring-celery-worker
  template:
    metadata:
      labels:
        app: agentspring-celery-worker
    spec:
      containers:
      - name: celery-worker
        image: agentspring:latest
        command: ["celery", "-A", "agentspring.celery_app.celery_app", "worker", "--loglevel=info"]
        envFrom:
        - configMapRef:
            name: agentspring-config
        - secretRef:
            name: agentspring-secrets 